# Automatically generated file. DO NOT MODIFY
#
# This file is generated by vendor/xiaomi/venus-miuicamera/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter arm64,$(TARGET_ARCH)),)
$(info Including AnxCamera for venus...)

endif
