# Automatically generated file. DO NOT MODIFY
#
# This file is generated by vendor/xiaomi/venus-miuicamera/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/venus-miuicamera/common

PRODUCT_COPY_FILES += \
    vendor/xiaomi/venus-miuicamera/common/proprietary/system/lib64/android.hardware.camera.common@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/android.hardware.camera.common@1.0.so \
    vendor/xiaomi/venus-miuicamera/common/proprietary/system/lib64/libSNPE.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libSNPE.so \
    vendor/xiaomi/venus-miuicamera/common/proprietary/system/lib64/libc++_shared.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libc++_shared.so \
    vendor/xiaomi/venus-miuicamera/common/proprietary/system/lib64/libcamera_algoup_jni.xiaomi.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libcamera_algoup_jni.xiaomi.so \
    vendor/xiaomi/venus-miuicamera/common/proprietary/system/lib64/libcamera_mianode_jni.xiaomi.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libcamera_mianode_jni.xiaomi.so \
    vendor/xiaomi/venus-miuicamera/common/proprietary/system/lib64/libcameraservice.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libcameraservice.so \
    vendor/xiaomi/venus-miuicamera/common/proprietary/system/lib64/libcdsprpc.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libcdsprpc.so \
    vendor/xiaomi/venus-miuicamera/common/proprietary/system/lib64/libdoc_photo.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libdoc_photo.so \
    vendor/xiaomi/venus-miuicamera/common/proprietary/system/lib64/libdoc_photo_c++_shared.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libdoc_photo_c++_shared.so \
    vendor/xiaomi/venus-miuicamera/common/proprietary/system/lib64/libhidltransport.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libhidltransport.so \
    vendor/xiaomi/venus-miuicamera/common/proprietary/system/lib64/libmialgo_ai_vision.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libmialgo_ai_vision.so \
    vendor/xiaomi/venus-miuicamera/common/proprietary/system/lib64/libmicampostproc_client.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libmicampostproc_client.so \
    vendor/xiaomi/venus-miuicamera/common/proprietary/system/lib64/libmotion_photo.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libmotion_photo.so \
    vendor/xiaomi/venus-miuicamera/common/proprietary/system/lib64/libmotion_photo_c++_shared.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libmotion_photo_c++_shared.so \
    vendor/xiaomi/venus-miuicamera/common/proprietary/system/lib64/libmotion_photo_mace.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libmotion_photo_mace.so \
    vendor/xiaomi/venus-miuicamera/common/proprietary/system/lib64/libopencl-camera.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libopencl-camera.so \
    vendor/xiaomi/venus-miuicamera/common/proprietary/system/lib64/vendor.qti.hardware.dsp@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vendor.qti.hardware.dsp@1.0.so \
    vendor/xiaomi/venus-miuicamera/common/proprietary/system/lib64/vendor.xiaomi.hardware.campostproc@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vendor.xiaomi.hardware.campostproc@1.0.so \
    vendor/xiaomi/venus-miuicamera/common/proprietary/system/priv-app/MiuiCamera/lib/arm/libCameraEffectJNI.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm/libCameraEffectJNI.so \
    vendor/xiaomi/venus-miuicamera/common/proprietary/system/priv-app/MiuiCamera/lib/arm/libarc_layer_sgl.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm/libarc_layer_sgl.so \
    vendor/xiaomi/venus-miuicamera/common/proprietary/system/priv-app/MiuiCamera/lib/arm/libcamera_arcsoft_handgesture.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm/libcamera_arcsoft_handgesture.so \
    vendor/xiaomi/venus-miuicamera/common/proprietary/system/priv-app/MiuiCamera/lib/arm/libcamera_handgesture_mpbase.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm/libcamera_handgesture_mpbase.so \
    vendor/xiaomi/venus-miuicamera/common/proprietary/system/priv-app/MiuiCamera/lib/arm/libcamera_sound_effect.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm/libcamera_sound_effect.so \
    vendor/xiaomi/venus-miuicamera/common/proprietary/system/priv-app/MiuiCamera/lib/arm/libhandengine.arcsoft.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm/libhandengine.arcsoft.so \
    vendor/xiaomi/venus-miuicamera/common/proprietary/system/priv-app/MiuiCamera/lib/arm/libmisoundcamerasupport.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm/libmisoundcamerasupport.so \
    vendor/xiaomi/venus-miuicamera/common/proprietary/system/priv-app/MiuiCamera/lib/arm/libmiuiblursdk.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm/libmiuiblursdk.so \
    vendor/xiaomi/venus-miuicamera/common/proprietary/system/priv-app/MiuiCamera/lib/arm/libmulti-wakeup-engine.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm/libmulti-wakeup-engine.so \
    vendor/xiaomi/venus-miuicamera/common/proprietary/system/priv-app/MiuiCamera/lib/arm64/libCameraEffectJNI.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64/libCameraEffectJNI.so \
    vendor/xiaomi/venus-miuicamera/common/proprietary/system/priv-app/MiuiCamera/lib/arm64/libOpenCL.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64/libOpenCL.so \
    vendor/xiaomi/venus-miuicamera/common/proprietary/system/priv-app/MiuiCamera/lib/arm64/libYuvWatermark.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64/libYuvWatermark.so \
    vendor/xiaomi/venus-miuicamera/common/proprietary/system/priv-app/MiuiCamera/lib/arm64/libanx.config.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64/libanx.config.so \
    vendor/xiaomi/venus-miuicamera/common/proprietary/system/priv-app/MiuiCamera/lib/arm64/libanx.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64/libanx.so \
    vendor/xiaomi/venus-miuicamera/common/proprietary/system/priv-app/MiuiCamera/lib/arm64/libarc_layer_sgl.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64/libarc_layer_sgl.so \
    vendor/xiaomi/venus-miuicamera/common/proprietary/system/priv-app/MiuiCamera/lib/arm64/libarcsoft_deflicker.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64/libarcsoft_deflicker.so \
    vendor/xiaomi/venus-miuicamera/common/proprietary/system/priv-app/MiuiCamera/lib/arm64/libcamera_960_mpbase.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64/libcamera_960_mpbase.so \
    vendor/xiaomi/venus-miuicamera/common/proprietary/system/priv-app/MiuiCamera/lib/arm64/libcamera_algoup_jni.xiaomi.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64/libcamera_algoup_jni.xiaomi.so \
    vendor/xiaomi/venus-miuicamera/common/proprietary/system/priv-app/MiuiCamera/lib/arm64/libcamera_arcsoft_handgesture.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64/libcamera_arcsoft_handgesture.so \
    vendor/xiaomi/venus-miuicamera/common/proprietary/system/priv-app/MiuiCamera/lib/arm64/libcamera_handgesture_mpbase.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64/libcamera_handgesture_mpbase.so \
    vendor/xiaomi/venus-miuicamera/common/proprietary/system/priv-app/MiuiCamera/lib/arm64/libcamera_mianode_jni.xiaomi.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64/libcamera_mianode_jni.xiaomi.so \
    vendor/xiaomi/venus-miuicamera/common/proprietary/system/priv-app/MiuiCamera/lib/arm64/libcamera_sound_effect.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64/libcamera_sound_effect.so \
    vendor/xiaomi/venus-miuicamera/common/proprietary/system/priv-app/MiuiCamera/lib/arm64/libcom.xiaomi.camera.requestutil.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64/libcom.xiaomi.camera.requestutil.so \
    vendor/xiaomi/venus-miuicamera/common/proprietary/system/priv-app/MiuiCamera/lib/arm64/libdeflicker_jni.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64/libdeflicker_jni.so \
    vendor/xiaomi/venus-miuicamera/common/proprietary/system/priv-app/MiuiCamera/lib/arm64/libhandengine.arcsoft.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64/libhandengine.arcsoft.so \
    vendor/xiaomi/venus-miuicamera/common/proprietary/system/priv-app/MiuiCamera/lib/arm64/libijkffmpeg.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64/libijkffmpeg.so \
    vendor/xiaomi/venus-miuicamera/common/proprietary/system/priv-app/MiuiCamera/lib/arm64/libijkplayer.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64/libijkplayer.so \
    vendor/xiaomi/venus-miuicamera/common/proprietary/system/priv-app/MiuiCamera/lib/arm64/libijksdl.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64/libijksdl.so \
    vendor/xiaomi/venus-miuicamera/common/proprietary/system/priv-app/MiuiCamera/lib/arm64/libmialgo_saliency.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64/libmialgo_saliency.so \
    vendor/xiaomi/venus-miuicamera/common/proprietary/system/priv-app/MiuiCamera/lib/arm64/libmialgo_saliency_jni.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64/libmialgo_saliency_jni.so \
    vendor/xiaomi/venus-miuicamera/common/proprietary/system/priv-app/MiuiCamera/lib/arm64/libmisoundcamerasupport.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64/libmisoundcamerasupport.so \
    vendor/xiaomi/venus-miuicamera/common/proprietary/system/priv-app/MiuiCamera/lib/arm64/libmiuiblursdk.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64/libmiuiblursdk.so \
    vendor/xiaomi/venus-miuicamera/common/proprietary/system/priv-app/MiuiCamera/lib/arm64/libmulti-wakeup-engine.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64/libmulti-wakeup-engine.so \
    vendor/xiaomi/venus-miuicamera/common/proprietary/system/priv-app/MiuiCamera/lib/arm64/libvideo_extra_color_converter.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64/libvideo_extra_color_converter.so \
    vendor/xiaomi/venus-miuicamera/common/proprietary/system/priv-app/MiuiCamera/lib/arm64/libvideo_extra_interpolator.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64/libvideo_extra_interpolator.so \
    vendor/xiaomi/venus-miuicamera/common/proprietary/system_ext/lib64/libcameraimpl.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/libcameraimpl.so \
    vendor/xiaomi/venus-miuicamera/common/proprietary/vendor/lib/vendor.qti.hardware.camera.device@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib/vendor.qti.hardware.camera.device@1.0.so \
    vendor/xiaomi/venus-miuicamera/common/proprietary/vendor/lib/vendor.qti.hardware.camera.device@3.5.so:$(TARGET_COPY_OUT_VENDOR)/lib/vendor.qti.hardware.camera.device@3.5.so \
    vendor/xiaomi/venus-miuicamera/common/proprietary/vendor/lib64/camera.device@1.0-impl.so:$(TARGET_COPY_OUT_VENDOR)/lib64/camera.device@1.0-impl.so \
    vendor/xiaomi/venus-miuicamera/common/proprietary/vendor/lib64/camera.device@3.2-impl.so:$(TARGET_COPY_OUT_VENDOR)/lib64/camera.device@3.2-impl.so \
    vendor/xiaomi/venus-miuicamera/common/proprietary/vendor/lib64/camera.device@3.3-impl.so:$(TARGET_COPY_OUT_VENDOR)/lib64/camera.device@3.3-impl.so \
    vendor/xiaomi/venus-miuicamera/common/proprietary/vendor/lib64/camera.device@3.4-external-impl.so:$(TARGET_COPY_OUT_VENDOR)/lib64/camera.device@3.4-external-impl.so \
    vendor/xiaomi/venus-miuicamera/common/proprietary/vendor/lib64/camera.device@3.4-impl.so:$(TARGET_COPY_OUT_VENDOR)/lib64/camera.device@3.4-impl.so \
    vendor/xiaomi/venus-miuicamera/common/proprietary/vendor/lib64/camera.device@3.5-external-impl.so:$(TARGET_COPY_OUT_VENDOR)/lib64/camera.device@3.5-external-impl.so \
    vendor/xiaomi/venus-miuicamera/common/proprietary/vendor/lib64/camera.device@3.5-impl.so:$(TARGET_COPY_OUT_VENDOR)/lib64/camera.device@3.5-impl.so \
    vendor/xiaomi/venus-miuicamera/common/proprietary/vendor/lib64/camera.device@3.6-external-impl.so:$(TARGET_COPY_OUT_VENDOR)/lib64/camera.device@3.6-external-impl.so \
    vendor/xiaomi/venus-miuicamera/common/proprietary/vendor/lib64/vendor.qti.hardware.camera.device@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib64/vendor.qti.hardware.camera.device@1.0.so \
    vendor/xiaomi/venus-miuicamera/common/proprietary/vendor/lib64/vendor.qti.hardware.camera.device@3.5.so:$(TARGET_COPY_OUT_VENDOR)/lib64/vendor.qti.hardware.camera.device@3.5.so

PRODUCT_PACKAGES += \
    MiuiCamera
